# DFUSE in-tree Razer HID driver

obj-$(CONFIG_HID_RAZER_DFUSE) += razer-dfuse.o

razer-dfuse-y := \
	razer-dfuse-main.o \
	compat.o \
	razercommon.o \
	razerchromacommon.o \
	razerkbd_driver.o \
	razermouse_driver.o
